export interface ThemeColors {
  background: string;
  surface: string;
  surfaceSecondary: string;
  surfaceElevated: string;
  card: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
  border: string;
  borderLight: string;
  primary: string;
  primaryDark: string;
  primaryLight: string;
  accent: string;
  error: string;
  errorLight: string;
  success: string;
  successLight: string;
  warning: string;
  warningLight: string;
  pending: string;
  pendingBg: string;
  accepted: string;
  acceptedBg: string;
  rejected: string;
  rejectedBg: string;
  overlay: string;
  white: string;
  navyDark: string;
  navyMedium: string;
  isDark: boolean;
  fontRegular: string;
  fontMedium: string;
  fontSemiBold: string;
  fontBold: string;
  fontTitle: string;
  tabBarBg: string;
  inputBg: string;
  inputBorder: string;
  headerBg: string;
  shadow: string;
}

export const LightTheme: ThemeColors = {
  background: "#F6F6F8",
  surface: "#FFFFFF",
  surfaceSecondary: "#F0F0F4",
  surfaceElevated: "#E8E8EC",
  card: "#FFFFFF",
  text: "#0A0A0A",
  textSecondary: "#444444",
  textTertiary: "#888888",
  border: "#E4E4E8",
  borderLight: "#F2F2F4",
  primary: "#DC2626",
  primaryDark: "#B91C1C",
  primaryLight: "#EF4444",
  accent: "#F87171",
  error: "#EF4444",
  errorLight: "#FEE2E2",
  success: "#16A34A",
  successLight: "#DCFCE7",
  warning: "#D97706",
  warningLight: "#FEF3C7",
  pending: "#D97706",
  pendingBg: "#FEF3C7",
  accepted: "#16A34A",
  acceptedBg: "#DCFCE7",
  rejected: "#DC2626",
  rejectedBg: "#FEE2E2",
  overlay: "rgba(0,0,0,0.5)",
  white: "#FFFFFF",
  navyDark: "#0A0A0A",
  navyMedium: "#1A1A1A",
  isDark: false,
  fontRegular: "Inter_400Regular",
  fontMedium: "Inter_500Medium",
  fontSemiBold: "Inter_600SemiBold",
  fontBold: "Inter_700Bold",
  fontTitle: "Michroma_400Regular",
  tabBarBg: "#FFFFFF",
  inputBg: "#FFFFFF",
  inputBorder: "#E4E4E8",
  headerBg: "#FFFFFF",
  shadow: "#000000",
};

export const DarkTheme: ThemeColors = {
  background: "#0A0A0A",
  surface: "#161616",
  surfaceSecondary: "#1C1C1C",
  surfaceElevated: "#242424",
  card: "#181818",
  text: "#F0F0F0",
  textSecondary: "#A8A8A8",
  textTertiary: "#666666",
  border: "#2A2A2A",
  borderLight: "#1E1E1E",
  primary: "#EF4444",
  primaryDark: "#DC2626",
  primaryLight: "#F87171",
  accent: "#F87171",
  error: "#F87171",
  errorLight: "rgba(239,68,68,0.18)",
  success: "#22C55E",
  successLight: "rgba(34,197,94,0.15)",
  warning: "#F59E0B",
  warningLight: "rgba(245,158,11,0.15)",
  pending: "#F59E0B",
  pendingBg: "rgba(245,158,11,0.15)",
  accepted: "#22C55E",
  acceptedBg: "rgba(34,197,94,0.15)",
  rejected: "#F87171",
  rejectedBg: "rgba(239,68,68,0.18)",
  overlay: "rgba(0,0,0,0.75)",
  white: "#FFFFFF",
  navyDark: "#F0F0F0",
  navyMedium: "#D0D0D0",
  isDark: true,
  fontRegular: "Inter_400Regular",
  fontMedium: "Inter_500Medium",
  fontSemiBold: "Inter_600SemiBold",
  fontBold: "Inter_700Bold",
  fontTitle: "Michroma_400Regular",
  tabBarBg: "#111111",
  inputBg: "#1C1C1C",
  inputBorder: "#2E2E2E",
  headerBg: "#111111",
  shadow: "#000000",
};

export const Colors = LightTheme;
export default Colors;
